.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo09 - Debug ]----------"
	@cd "C:\LabEDD\Ejemplo09" && "$(MAKE)" -f  "Ejemplo09.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo09 - Debug ]----------"
	@cd "C:\LabEDD\Ejemplo09" && "$(MAKE)" -f  "Ejemplo09.mk" clean
